import os
import time
os.system('clear')

def clear():
	os.system('clear')

screen = input("wich start up screen animation would you like? (1, ect)?: ")

if screen == "1":
	clear()
	os.system('toilet B')
	time.sleep(1)
	clear()
	os.system('toilet BA')
	time.sleep(1)
	clear()
	os.system('toilet BAL')
	time.sleep(1)
	clear()
	os.system('toilet BALL')
	time.sleep(1)
	clear()
	os.system('toilet BALLS')
	time.sleep(2)
	print("big black balls nigga :3")

elif screen == "2":
	clear()
	os.system('toilet F')
	time.sleep(1)
	clear()
	os.system('toilet FE')
	time.sleep(1)
	clear()
	os.system('toilet FEM')
	time.sleep(1)
	clear()
	os.system('toilet FEMB')
	time.sleep(1)
	clear()
	os.system('toilet FEMBO')
	time.sleep(1)
	clear()
	os.system('toilet FEMBOY')
	time.sleep(0.3)
	clear()
	os.system('toilet YOBMEF')
	time.sleep(0.3)
	clear()
	os.system('toilet FEMBOY')
	time.sleep(1)
	os.system('toilet SEX')
	print("on top")